name: flutter_lockscreen_alert
description: >-
  Flutter plugin to show critical alert UI on the device lock screen using
  Android full-screen intents. Ideal for incoming calls, bookings, or
  time-sensitive alerts that must be visible and interactive when the screen
  is locked.
version: 1.0.1
homepage: https://github.com/vairagadeharshwardhan/flutter_lockscreen_alert
repository: https://github.com/vairagadeharshwardhan/flutter_lockscreen_alert
issue_tracker: https://github.com/vairagadeharshwardhan/flutter_lockscreen_alert/issues
documentation: https://github.com/vairagadeharshwardhan/flutter_lockscreen_alert#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.plugins.lockscreen_alert
        pluginClass: FlutterLockscreenAlertPlugin
      ios:
        pluginClass: FlutterLockscreenAlertPlugin
